project_id = "djmkzsxsfwyrqmhcgsyx"

[functions.approve-video]
verify_jwt = true

[functions.call-n8n-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.diagnostic]
verify_jwt = false

[functions.log-health-check]
verify_jwt = false

[functions.generate-video]
verify_jwt = true

[functions.handle-approval-response]
verify_jwt = false

[functions.handle-payment-success]
verify_jwt = false

[functions.handle-video-webhook]
verify_jwt = false

[functions.process-video-uploads]
verify_jwt = true

[functions.refresh-social-tokens]
verify_jwt = true

[functions.submit-video]
verify_jwt = true

[functions.trigger-n8n-webhook]
verify_jwt = false

[functions.upload-to-instagram]
verify_jwt = true

[functions.upload-to-tiktok]
verify_jwt = true

[functions.upload-to-youtube]
verify_jwt = true

[functions.video-ready]
verify_jwt = true

[functions.youtube-oauth]
verify_jwt = false

[functions.youtube-oauth-initiate]
verify_jwt = true